### ISSUE TITLE
加载更多时，最后几个item有可能消失

### ISSUE THREAD

**Issue by BaronZ** [bingoogolapple/BGARefreshLayout-Android#10]
上拉加载更多时，在刷新的过程中，最后几个item有可能消失，等到加载完成时，数据恢复正常

**Comment by nannancat** [comment]
我碰到了同样的问题，有解决方案吗？

**Comment by nannancat** [comment]
demo中的NormalRecyclerViewDemoActivity也有此问题，当调用onBGARefreshLayoutBeginLoadingMore后，最后一项item会消失，当跑到endLoadingMore()时，数据显示恢复正常

**Comment by bingoogolapple** [comment]
@BaronZ @nannancat 当内容视图是RecyclerView，并且大于1列时，确实会有这个问题

**Comment by BaronZ** [comment]
有没有计划修复这个Bug?

**Comment by BaronZ** [comment]
版本号没有增加？

**Comment by BaronZ** [comment]
看到了
