### ISSUE TITLE
java.lang.RuntimeException: BGARefreshLayout必须有且只有一个子控件

### ISSUE THREAD

**Issue by guoyoujin** [bingoogolapple/BGARefreshLayout-Android#17]
java.lang.RuntimeException: BGARefreshLayout必须有且只有一个子控件     atcn.bingoogolapple.refreshlayout.BGARefreshLayout.onFinishInflate(BGARefreshLayout.java:158)
          是否可以做成不限制里面的子控件啊

**Comment by bingoogolapple** [comment]
@guoyoujin 布局文件中写的时候必须只且只有一个子控件，代码中可以通过setCustomHeaderView方法设置头部的布局
