### ISSUE TITLE
BGARefreshLayout-Android与viewpager联合使用时底部加载更多无法显示

### ISSUE THREAD

**Issue by linuxjava** [bingoogolapple/BGARefreshLayout-Android#18]
viewpager中包含fragment，fragment中BGARefreshLayout内部有listview，滑动到底部加载更多时，底部加载更多视图无法显示

**Comment by ljnalex** [comment]
同问，我也有这个问题

**Comment by answer1989** [comment]
我也遇到同样地问题了，有解决方法吗？

**Comment by bingoogolapple** [comment]
这种场景还没试过，BGARefreshLayout是设置的高度自适应吗？

**Comment by answer1989** [comment]
不是BGARefreshLayout是设置match_parent的，不过他是在一个viewpager的fragment布局中的，不知道有没有影响

**Comment by answer1989** [comment]
我调试了一下，footer loading view的高度也能拿到，是在显示visible的时候没有显示出来

**Comment by linuxjava** [comment]
内容控件的高度设置的android:layout_height="0dp"和android:layout_weight="1"，不在viewpager中使用的话就没问题；肯定是兼容的问题的，因为pulltorefrrsh也是要兼容viewpager的

**Comment by CentMeng** [comment]
同问此问题，是在viewpager中的fragment中使用，而且rececleview使用android:layout_height="0dp"和android:layout_weight="1"

**Comment by hunji66** [comment]
同遇到此问题。。

**Comment by CentMeng** [comment]
我的解决方案是在viewholder下面加上拉加载更多

**Comment by hunji66** [comment]
什么意思啊。。能详细说明一下么？谢谢啦

**Comment by CentMeng** [comment]
你把下拉加载更多的layout放在viewpager下面

**Comment by hunji66** [comment]
就是我写在viewpage的下面 而不是对应fragment里面么?

**Comment by bingoogolapple** [comment]
@linuxjava @ljnalex @answer1989 @CentMeng @hunji66  请查看 https://github.com/bingoogolapple/BGARefreshLayoutDemo
