### ISSUE TITLE
下拉刷新的时候，能设置 pull 的距离吗？

### ISSUE THREAD

**Issue by HelloVass** [bingoogolapple/BGARefreshLayout-Android#20]
可以给用户拉动的距离太短了，感觉用户体验不太好呢？作者有设置这样的接口吗?

**Comment by bingoogolapple** [comment]
@HelloVass 可以设置

> [BGARefreshViewHolder源码中有下面这段](https://github.com/bingoogolapple/BGARefreshLayout-Android/blob/master/library/src/main/java/cn/bingoogolapple/refreshlayout/BGARefreshViewHolder.java) 

```Java
    /**
     * 下拉刷新控件paddingTop的弹簧距离与下拉刷新控件高度的比值
     */
    private static final float SPRING_DISTANCE_SCALE = 0.4f;
    /**
     * 下拉刷新控件paddingTop的弹簧距离与下拉刷新控件高度的比值，默认0.4f
     */
    private float mSpringDistanceScale = SPRING_DISTANCE_SCALE;

    /**
     * 设置下拉刷新控件paddingTop的弹簧距离与下拉刷新控件高度的比值，不能小于0，如果刷新控件比较高，建议将该值设置小一些
     *
     * @param springDistanceScale
     */
    public void setSpringDistanceScale(float springDistanceScale) {
        if (springDistanceScale < 0) {
            throw new RuntimeException("下拉刷新控件paddingTop的弹簧距离与下拉刷新控件高度的比值springDistanceScale不能小于0");
        }
        mSpringDistanceScale = springDistanceScale;
    }
```

> 使用方法

```Java
    BGANormalRefreshViewHolder normalRefreshViewHolder = new BGANormalRefreshViewHolder(this, true);
    normalRefreshViewHolder.setSpringDistanceScale(根据你的需要设置大于0的float值)；
```

**Comment by HelloVass** [comment]
@bingoogolapple thanks,我那时候傻逼了，明明看到了源码中有这个方法，但是我居然以为是继承 BGARefreshViewHolder 然后覆写这个方法：
 ```
@Override
    public void setSpringDistanceScale(float springDistanceScale) {
        super.setSpringDistanceScale(200);
    }
 ```

哎，真是麻烦楼主大大了，是我的锅。

**Comment by HelloVass** [comment]
@Override
public boolean onInterceptTouchEvent(MotionEvent event) {
    switch (event.getAction()) {
        case MotionEvent.ACTION_DOWN:
            mInterceptTouchDownX = event.getRawX();
            mInterceptTouchDownY = event.getRawY();
            break;
        case MotionEvent.ACTION_MOVE:
            if (!mIsLoadingMore && (mCurrentRefreshStatus != RefreshStatus.REFRESHING)) {
                if (mInterceptTouchDownX == -1) {
                    mInterceptTouchDownX = (int) event.getRawX();
                }
                if (mInterceptTouchDownY == -1) {
                    mInterceptTouchDownY = (int) event.getRawY();
                }

                int interceptTouchMoveDistanceY = (int) (event.getRawY() - mInterceptTouchDownY);
                // 可以没有上拉加载更多，但是必须有下拉刷新，否则就不拦截事件
                if (Math.abs(event.getRawX() - mInterceptTouchDownX) < Math.abs(interceptTouchMoveDistanceY) && mRefreshHeaderView != null) {
                    if ((interceptTouchMoveDistanceY > 0 && shouldHandleRefresh()) || (interceptTouchMoveDistanceY < 0 && shouldHandleLoadingMore()) || interceptTouchMoveDistanceY < 0 && !isWholeHeaderViewCompleteInvisible()) {
                        // ACTION_DOWN时没有消耗掉事件，子控件会处于按下状态，这里设置ACTION_CANCEL，使子控件取消按下状态
                        event.setAction(MotionEvent.ACTION_CANCEL);
                        super.onInterceptTouchEvent(event);
                        return true;
                    }
                }
            }
            break;


我最近在使用作者的 BGARefreshLayout ，发现 issue#13 提出的 
下拉刷新的时候头部固定不动，无法上滑，用户体验不是特别好
确实需要修正。在刷新中的时候会，Header 固定，用户向上推动 Header，但是 Header 还是卡在那里，给人一种迟钝的感觉。正题来了，我想请教一下作者，是不是在这段代码中判断 （处于下拉刷新中&&用户向上推动header），在 onInterceptTouchEvent（） 返回 true，将 event 中断，自己处理，就可以解决？
