### ISSUE TITLE
下拉刷新头部无法出现

### ISSUE THREAD

**Issue by xym0519** [bingoogolapple/BGARefreshLayout-Android#25]
1.1.0版本，当嵌套recycleview时，如果第一个单元格的高度过大（超出一屏），会导致下拉刷新的头部出不来，我尝试着定位了一下问题，发现在ScrollingUtil.java(63)处，layoutManager.findFirstCompletelyVisibleItemPosition()方法获取到的值始终为-1，导致判定失效，我试着加入了==-1的判定条件，现在头部是可以出来了，但是不确定是否对其他部分会造成影响

**Comment by bingoogolapple** [comment]
ScrollingUtil.java的63和70行都改成了小于1，你改成小于1试试你那边的各种情况能不能成功，都成功的话我发个新版到jcenter

**Comment by xym0519** [comment]
我这边将你说的那两行的判定条件都改为了<1， 测试了第一个单元格:
1、高度指定为wrap_content时，高度超出一屏
2、手动指定高度为1000dp时，高度超出一屏
3、高度指定为wrap_content时，高度未超出一屏
4、手动指定高度为100dp时，高度未超出一屏
以上情况下，都能如预期的工作，并且未出现其他异常的表现

**Comment by bingoogolapple** [comment]
好哒，待会传jcenter
