### ISSUE TITLE
 BGARefreshLayout＋BGAStickyNavLayout问题。求解

### ISSUE THREAD

**Issue by 1024iCloud** [bingoogolapple/BGARefreshLayout-Android#29]
### 超出后
![fda01eb6-9a57-4aa2-919d-4718fd678df3](https://cloud.githubusercontent.com/assets/10859832/11524625/22134954-9907-11e5-9c26-39ead92686a3.png)

### 原始图
![Uploading C495D7B7-0FCD-4557-83EC-1E8ACD0C29CA.png…]()

当BGAStickyNavLayout 中的第一个子View高度超出屏幕的高度是，只能下拉，布局不能往上走，当在下拉的时候拖动布局是，可以看出层次错误了。

### 第一个子view超过屏幕高度后，超出的不显示，而且下面的布局会被遮挡，第二个和第三个会向上padding掉第一个子view超出屏幕的距离

**Comment by chinume** [comment]
以解决

**Comment by bingoogolapple** [comment]
@1024iCloud 现在解决了吗？

**Comment by 1024iCloud** [comment]
@bingoogolapple 解决了，
你的代码限定了第三个view的高度，其他两个随父类调节，我稍微改了下上面的view变成自适应的那种
:smile:
