### ISSUE TITLE
有没有提供一个方法，用代码进行刷新

### ISSUE THREAD

**Issue by BaronZ** [bingoogolapple/BGARefreshLayout-Android#3]
你好
有没有提供一个方法，用代码进行刷新？
使用场景是我进入一个页面，要代码调用刷新，显示加载中...

**Comment by BaronZ** [comment]
看到了你添加了`beginRefreshing();`
为什么里面不直接调用`onBGARefreshLayoutBeginRefreshing(mRefreshLayout);`?
一般有这个需求，就是要手动调用beginRefreshing自动加载内容的，你这里相当于只是一个效果

**Comment by BaronZ** [comment]
还有一个疑问，为什么`onBGARefreshLayoutBeginRefreshing()` 要加入`BGARefreshLayout`参数？

**Comment by BaronZ** [comment]
第三个问题是：能否提供EmptyView,和ErrorView

**Comment by bingoogolapple** [comment]
@BaronZ 是模拟的iOS中自带的UIRefreshControl

**Comment by BaronZ** [comment]
`@BaronZ 是模拟的iOS中自带的UIRefreshControl`
这一句是回复什么的？

**Comment by bingoogolapple** [comment]
@BaronZ 除了“还有，能否提供EmptyView,和ErrorView”

**Comment by BaronZ** [comment]
我碰到一个很奇怪的问题，我的代码里，请求网络时，如果网络没连接，我会调用endRefreshing()
`
if(!isNetworkAvailable(context)){
    layout.endRefreshing();
}
`,但是没有效果(即那个圈圈仍旧一直在加载)，如果我单独起一个AsyncTask,endRefreshing在onPostExecute里面调用才有效果
