### ISSUE TITLE
建议模块化

### ISSUE THREAD

**Issue by vipheyue** [bingoogolapple/BGARefreshLayout-Android#31]
能不能把每个效果,分包,相对独立出来,不然文件东扯西扯的,用起来也麻烦,而且有baseactiviy,引用起来扯的东西更多.android-pulltorefresh sample很明了,可以参考一下,作为普通开发人员,引用你的lib,真心觉得好累

**Comment by huclengyue** [comment]
我觉得挺好的啊。。还算清晰啊。。。。

**Comment by vipheyue** [comment]
我表示弄了20分钟都没有弄好,没有独立出来,八base 类,,..拖了一个托第二个 都没有搞好

**Comment by vipheyue** [comment]
单独的一个效果,是单独的一个包,这个最好了..引用和看起来都比较方便,当然我是建议 3Q
