### ISSUE TITLE
加载更多无效？

### ISSUE THREAD

**Issue by pickyourself** [bingoogolapple/BGARefreshLayout-Android#32]
加载更多无效？

**Comment by MrChangyaohua** [comment]
补充：
实验了很久，一个奇怪的现象，在fragment中，把BGARefreshLayout和recyclerview的初始化放在了onViewCreated，如果把初始化放在onCreateView就没问题

**Comment by Idtk** [comment]
我遇到了相同的情况，在fragment中，在onCreateView中进行初始化，出现了问题。在Android 4.4 版本的情况下，无法加载更多数据，不显示动画；在Android 5.0版本的情况下，可以加载更多数据，但是依旧无法显示动画。

**Comment by loshine** [comment]
相同的情况，使用在Fragment中使用BGARefreshLayout嵌套RecyclerView，无法使用加载更多功能

**Comment by bingoogolapple** [comment]
在Fragment的onCreateView里初始化BGARefreshlayout，不要在onActivityCreated里初始化
