### ISSUE TITLE
请教上拉动画显示的问题

### ISSUE THREAD

**Issue by zjyangyong** [bingoogolapple/BGARefreshLayout-Android#33]
工程中只引入了 
compile 'com.android.support:recyclerview-v7:23.1.1'
compile 'com.nineoldandroids:library:2.4.0'
compile 'cn.bingoogolapple:bga-refreshlayout:1.1.2@aar'
这个三个库, 
刷新ViewHolder设置成 BGARefreshViewHolder refreshViewHolder = new BGANormalRefreshViewHolder(context, true);
bgaRefreshLayout.setIsShowLoadingMoreView(true);也设置为true
但是上拉刷新的 footview 显示不出来求解原因? 是否和DEMO中没有引入其他库有关系?
谢谢

**Comment by bingoogolapple** [comment]
布局文件中内容视图的高度有没有设置成高度自适应

```xml
<!-- 内容控件 -->
    <AnyView
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1" />
```

**Comment by zjyangyong** [comment]
这个有添加的
<ListView
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:divider="@android:color/transparent"

**Comment by zjyangyong** [comment]
找到原因了,onBGARefreshLayoutBeginLoadingMore()返回值设置成ture就正常了,感谢答疑!
