### ISSUE TITLE
ViewPagerDemo中viewPager中的recyclerView滑动问题

### ISSUE THREAD

**Issue by feiyangbahu1** [bingoogolapple/BGARefreshLayout-Android#34]
如果recyclerView中数据只有一个或者不满一屏的话，上拉加载时，recyclerView滑不上去，使得一部分数据展示不出来，如果上拉加载无数据时，会一直响应上拉加载的动作

**Comment by bingoogolapple** [comment]
@feiyangbahu1 这个问题现在解决了吗，用最新版v1.1.3试一下

**Comment by feiyangbahu1** [comment]
现在可以了
