### ISSUE TITLE
怎么实现已查看条目变灰色？

### ISSUE THREAD

**Issue by lgb020** [bingoogolapple/BGARefreshLayout-Android#36]
怎么实现已查看条目变灰色？

**Comment by bingoogolapple** [comment]
@lgb020 撒意思

**Comment by lgb020** [comment]
就是我用BGARefreshLayout实现了一个下拉刷新列表，类似于今日头条，就是资讯类的。
但是我现在想要实现用户点击过后当前条目变成灰色，用于区分已经阅读和没有阅读。
我已经实现了当进来后点击的话是可以变色的。但是，关闭Activity再打开时，怎么在初始化的时候把某条记录 view.setSelected(true);
效果如下图：



简单的说就是：我怎么样在列表初始化之后再去获得某个行的view对象。
谢谢。我是Android的初学者.




------------------ 原始邮件 ------------------
发件人: "王浩";<notifications@github.com>;
发送时间: 2016年1月14日(星期四) 晚上11:56
收件人: "bingoogolapple/BGARefreshLayout-Android"<BGARefreshLayout-Android@noreply.github.com>; 
抄送: "标"<lgb020@qq.com>; 
主题: Re: [BGARefreshLayout-Android] 怎么实现已查看条目变灰色？ (#36)




@lgb020 撒意思

**Comment by bingoogolapple** [comment]
@lgb020 在你数据模型里加个字段表示是否已经阅读过就好，在adapter的getView方法里根据那个字段来设置条目颜色
