### ISSUE TITLE
能否添加一个加载完成后显示"没有更多了/加载完毕"的底部视图

### ISSUE THREAD

**Issue by qinjuning** [bingoogolapple/BGARefreshLayout-Android#37]
Hi bingoogolapple : 

  现在加载完毕后，没有类似"没有更多/加载完毕"的底部视图，导致交互较为差劲。因为一般的app数据都是有限的，有个类似"没有更多了/加载完毕"的显示比较好。 当下拉刷新的时候 加载更多的时候 隐藏该视图， 如果能提供自定义该视图相关接口就更好了。

  麻烦有时间在1.3.4版本能否添加下。 3Q

**Comment by bingoogolapple** [comment]
@qinjuning  没有这次这个功能哈，没有更多就弹吐司提示用户吧。

不过你可以尝试继承BGARefreshViewHolder类，在自定义其中的LoadingMoreView，该视图中包含加载更多视图和没有更多了的视图，根据服务端返回的数据，自己控制显示状态
