### ISSUE TITLE
点击好像受到下拉的影响，不好点了

### ISSUE THREAD

**Issue by fanxl12** [bingoogolapple/BGARefreshLayout-Android#39]
下拉里面放一个listview，点击item的时候，如果不是精确点击，它会被识别成要下拉，整个界面有轻微的向下滚动，但是实际上用户是想点击，所以会出现点击没反应的情况，而用原生的listview就没这种情况，希望优化一下

**Comment by echolong** [comment]
可以在BGARefreshLayout的onInterceptTouchEvent 方法中把 灵敏度调低点，
if (Math.abs(interceptTouchMoveDistanceX) < Math.abs(interceptTouchMoveDistanceY) && mRefreshHeaderView != null) {
                        if ((interceptTouchMoveDistanceY > 20 && shouldHandleRefresh())
                                || (interceptTouchMoveDistanceY < -20 && shouldHandleLoadingMore())
                                || interceptTouchMoveDistanceY < -20 && !isWholeHeaderViewCompleteInvisible()) {

**Comment by fanxl12** [comment]
有提供方法修改吗？还是只能下载源码进行修改？
