### ISSUE TITLE
有什么方法可以关闭“下拉加载”功能？

### ISSUE THREAD

**Issue by WaylanPunch** [bingoogolapple/BGARefreshLayout-Android#4]
例如当前界面item个数是确定的，我只需要下拉刷新item里的数据，不需要下拉加载更多item

**Comment by BaronZ** [comment]
BGARefreshViewHolder(Context context, boolean isLoadingMoreEnabled) 
这个构造方法设置

**Comment by WaylanPunch** [comment]
谢谢啊
