### ISSUE TITLE
开放返回当前状态

### ISSUE THREAD

**Issue by sduqlsc** [bingoogolapple/BGARefreshLayout-Android#40]
最好加一个返回当前的状态的方法，如getCurrentRefreshStatus~

另，现在还有些在无数据的时候显示一张图片或者其他的布局的，是否可以增加这种功能或者适配一下ViewAnimator?

**Comment by oYo-Byte** [comment]
+1,希望能有返回当前状态的方法，因为发现有时 loadMore没有触发到，不知是什么原因，如果有 返回当前状态的方法 的话可以 自定义控制的时候 不造成冲突
