### ISSUE TITLE
fragment中使用刷新控件 上拉有问题

### ISSUE THREAD

**Issue by jobscolin** [bingoogolapple/BGARefreshLayout-Android#42]
当在fragment中使用刷新控件时，在onActivityCreated（）方法中初始化刷新控件，上拉不能实现，下拉可以，在onCreateView（）中初始化刷新控件则上拉下拉都可以？BUG ????

**Comment by bingoogolapple** [comment]
@jobscolin  在Fragment的onCreateView里初始化BGARefreshlayout，不要在onActivityCreated里初始化

**Comment by jobscolin** [comment]
OK
