### ISSUE TITLE
不显示加载更多的View

### ISSUE THREAD

**Issue by WongLu** [bingoogolapple/BGARefreshLayout-Android#44]
你好，通过BGANormalRefreshViewHolder设置下拉刷新加载更多的风格时，加载更多的时候，无法显示正在加载的view，数据会显示出来，是我没使用对吗?

**Comment by bingoogolapple** [comment]
注意看README中说的内容控件高度自适应 layout_weight＝1     layout_height＝0

再不行就加群来问 群号码：196281253

**Comment by WongLu** [comment]
单独在一个activity里用BGANormalRefreshViewHolder风格时没有问题，下拉刷新加载更多都可以。
如果在DrawerLayout  的内容界面通过Viewpager显示fragment ，Fragment 中用下拉刷新和加载更多的时候，加载更多就会显示不出圆形进度条。

**Comment by bingoogolapple** [comment]
我demo里也是用的DrawerLayout+ViewPager+Fragment，研究下demo里是怎样做的。再研究不出来就加群来问 群号码：196281253

**Comment by bingoogolapple** [comment]
@WongLu  在Fragment的onCreateView里初始化BGARefreshlayout，不要在onActivityCreated里初始化

**Comment by WongLu** [comment]
@bingoogolapple 谢谢。

**Comment by bingoogolapple** [comment]
@WongLu 这个问题现在解决了吗？

**Comment by WongLu** [comment]
@bingoogolapple 解决了。谢谢！
