### ISSUE TITLE
使用ItemDecoration设置top后下滑失效

### ISSUE THREAD

**Issue by David44144** [bingoogolapple/BGARefreshLayout-Android#46]
让第一个项目top设置为100后，下拉失效

mDataRv.addItemDecoration(new Divider(mApp));

public class Divider extends RecyclerView.ItemDecoration {
    private Drawable mDividerDrawable;

    public Divider(Context context) {
        mDividerDrawable = context.getResources().getDrawable(R.mipmap.list_divider);
    }
    
    @Override
    public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {
        if (parent.getChildLayoutPosition(view) == 0) {
            outRect.set(0, 100, 0, 0);
        }
    }

    @Override
    public void onDrawOver(Canvas c, RecyclerView parent, RecyclerView.State state) {
        drawVertical(c, parent);
    }
}

**Comment by Kilnn** [comment]
I have this problem too.
