### ISSUE TITLE
recyclerView.addItemDecoration 之后无法下拉刷新

### ISSUE THREAD

**Issue by BaronZ** [bingoogolapple/BGARefreshLayout-Android#6]
recyclerView.addItemDecoration 之后无法下拉刷新

**Comment by bingoogolapple** [comment]
@BaronZ 是什么样的场景？ [NormalRecyclerViewDemoActivity](https://github.com/bingoogolapple/BGARefreshLayout-Android/blob/master/demo/src/main/java/cn/bingoogolapple/refreshlayout/demo/activity/NormalRecyclerViewDemoActivity.java)   这里面第60行也是addItemDecoration，可以下拉刷新

**Comment by BaronZ** [comment]
`
public class SpacesItemDecoration extends RecyclerView.ItemDecoration {
    private int space;

    public SpacesItemDecoration(int space) {
        this.space = space;
    }

    @Override
    public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {
        outRect.left = space;
        outRect.right = space;
        outRect.bottom = space;

        // Add top margin only for the first item to avoid double space between items
        if(parent.getChildPosition(view) == 0)
            outRect.top = space;
    }
}
`

**Comment by BaronZ** [comment]
代码如下

    public class SpacesItemDecoration extends RecyclerView.ItemDecoration {

    private int space;

    public SpacesItemDecoration(int space) {
        this.space = space;
    }

    @Override
    public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {
        outRect.left = space;
        outRect.right = space;
        outRect.bottom = space;

        // Add top margin only for the first item to avoid double space between items
        if(parent.getChildPosition(view) == 0)
            outRect.top = space;
    }
}

**Comment by bingoogolapple** [comment]
@BaronZ 你参考[Divider](https://github.com/bingoogolapple/BGARefreshLayout-Android/blob/master/demo/src/main/java/cn/bingoogolapple/refreshlayout/demo/widget/Divider.java)试试看

**Comment by kuake** [comment]
设置上边时：outRect.set(0, 30, 0, 0), 下拉刷新失效
