### ISSUE TITLE
底部放置个底部导航，自定义加载在中间，显示不出来加载更多。

### ISSUE THREAD

**Issue by PossibleZero** [bingoogolapple/BGARefreshLayout-Android#60]
有什么自定义加载更多或者其他的方法吗，加载更多显示不出来。

**Comment by PossibleZero** [comment]
有什么方案能够解决吗，在线等，急，谢谢啦。

**Comment by bingoogolapple** [comment]
@PossibleZero 是在fragment中使用吗？
顺便贴一下你的布局文件来看一下

**Comment by PossibleZero** [comment]
hi，博主，我现在用的fragment，中嵌套了一个viewpager，viewpager里面加载的都是fragment，现在遇到的问题是，我上拉或者下拉，一直有加载状态，我通过回调，调用最外层的Fragment中的endRefreshing()，不起作用，依然是在那里转。
FragmentHome中的调用方法` @Override
    public void onBGARefreshLayoutBeginRefreshing(BGARefreshLayout refreshLayout) {
        switch (viewPager.getCurrentItem()) {
            case 0:
                cheeseListFragment.onBGARefreshLayoutBeginRefreshing(refreshLayout);
                break;
        }

    }

    @Override
    public boolean onBGARefreshLayoutBeginLoadingMore(BGARefreshLayout refreshLayout) {
        switch (viewPager.getCurrentItem()) {
            case 0:
                return cheeseListFragment.onBGARefreshLayoutBeginLoadingMore(refreshLayout);
        }
        return false;
    }

    public void endRefreshing() {
        if (mRefreshLayout != null) {
            mRefreshLayout.endRefreshing();
        }
    }

    public void endLoadingMore() {
        if (mRefreshLayout != null) {
            mRefreshLayout.endLoadingMore();
        }
    }
`

子的Fragment中的实现：
`  @Override
    public void onBGARefreshLayoutBeginRefreshing(BGARefreshLayout refreshLayout) {
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                iLoadingendListener.endRefreshingTab();
            }
        }, 1000);
    }

    @Override
    public boolean onBGARefreshLayoutBeginLoadingMore(BGARefreshLayout refreshLayout) {
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                iLoadingendListener.endLoadingMoreTab();
            }
        }, 1000);


        return true;
    }`
实现原理是通过回调方法调用最外层中的方法，回调方法有相应，依然没有终止继续旋转。
麻烦了。

**Comment by PossibleZero** [comment]
`<cn.bingoogolapple.refreshlayout.BGARefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/refreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:orientation="vertical">


    <cn.bingoogolapple.refreshlayout.BGAStickyNavLayout
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:orientation="vertical">


        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <TextView
                android:id="@+id/title_info"
                android:layout_width="wrap_content"
                android:layout_height="50dp"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                android:background="@color/white"
                android:gravity="center"
                android:text="@string/home_common_top_title"
                android:textSize="17sp"
                android:textStyle="bold"
                android:typeface="sans" />

            <View
                android:id="@+id/banner"
                android:layout_width="match_parent"
                android:layout_height="190dp" />

        </LinearLayout>


        <cn.bingoogolapple.bgaindicator.BGAFixedIndicator
            android:id="@+id/indicator"
            android:layout_width="match_parent"
            android:layout_height="40dp"
            android:layout_marginBottom="0dp"
            android:layout_marginTop="0dp"
            android:background="@color/white"
            android:paddingBottom="0dp"
            android:paddingTop="0dp"
            app:indicator_dividerColor="@color/colorPrimaryDarkTrans"
            app:indicator_dividerVerticalMargin="5dp"
            app:indicator_dividerWidth="2dp"
            app:indicator_hasDivider="false"
            app:indicator_textColor="@color/tab_txt_sel"
            app:indicator_textSizeNormal="12sp"
            app:indicator_textSizeSelected="14sp"
            app:indicator_triangleColor="@color/color_333333"
            app:indicator_triangleHeight="2dp"
            app:indicator_triangleHorizontalMargin="5dp" />


        <android.support.v4.view.ViewPager
            android:id="@+id/view_pager"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </cn.bingoogolapple.refreshlayout.BGAStickyNavLayout>
</cn.bingoogolapple.refreshlayout.BGARefreshLayout>
`
布局文件是这样的.

**Comment by PossibleZero** [comment]
找了下原因，不知道是不是跟这个有关，我的baseFragment是这样定义的，
`<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/fl_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <include
        android:id="@+id/loading"
        layout="@layout/common_loading_gif"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="gone" />

    <include
        android:id="@+id/net_error"
        layout="@layout/weak_network_interface"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="gone" />

</FrameLayout>`

**Comment by PossibleZero** [comment]
每个子的内容，add到fl_container中的，现在有个问题是，下拉刷新，刷新不出来，上拉加载有效果；而且在父类的
`<cn.bingoogolapple.refreshlayout.BGARefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/refreshLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:orientation="vertical">


    <cn.bingoogolapple.refreshlayout.BGAStickyNavLayout
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:orientation="vertical">


        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <TextView
                android:id="@+id/title_info"
                android:layout_width="wrap_content"
                android:layout_height="50dp"
                android:layout_centerInParent="true"
                android:layout_gravity="center"
                android:background="@color/white"
                android:gravity="center"
                android:text="@string/home_common_top_title"
                android:textSize="17sp"
                android:textStyle="bold"
                android:typeface="sans" />

            <View
                android:id="@+id/banner"
                android:layout_width="match_parent"
                android:layout_height="190dp" />

        </LinearLayout>


        <cn.bingoogolapple.bgaindicator.BGAFixedIndicator
            android:id="@+id/indicator"
            android:layout_width="match_parent"
            android:layout_height="40dp"
            android:layout_marginBottom="0dp"
            android:layout_marginTop="0dp"
            android:background="@color/white"
            android:paddingBottom="0dp"
            android:paddingTop="0dp"
            app:indicator_dividerColor="@color/colorPrimaryDarkTrans"
            app:indicator_dividerVerticalMargin="5dp"
            app:indicator_dividerWidth="2dp"
            app:indicator_hasDivider="false"
            app:indicator_textColor="@color/tab_txt_sel"
            app:indicator_textSizeNormal="12sp"
            app:indicator_textSizeSelected="14sp"
            app:indicator_triangleColor="@color/color_333333"
            app:indicator_triangleHeight="2dp"
            app:indicator_triangleHorizontalMargin="5dp" />


        <android.support.v4.view.ViewPager
            android:id="@+id/view_pager"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </cn.bingoogolapple.refreshlayout.BGAStickyNavLayout>
</cn.bingoogolapple.refreshlayout.BGARefreshLayout>
`

Banner部分有时候，滑动上去以后，就再也滑动不下来了，不知道是不是还在加载的问题。

**Comment by PossibleZero** [comment]
我试了下找到问题的原因了，跟我写的BaseFragment有关，我基类为了处理loading，和网络异常的处理逻辑，只是我不太明白，为啥这样的原因；
onCreateView的时候加载了自己定义的布局，我是将布局add进去的。
`FrameLayout containerView = (FrameLayout) inflate.findViewById(R.id.fl_container);
        int contentId = getContentLayoutId();
        if (contentId > 0) {
            mContentView = LayoutInflater.from(getActivity()).inflate(contentId, null);
            containerView.addView(mContentView, 0);`
现在造成的影响是，上拉加载能显示出来，下拉加载显示不出来，并且上部滑动到上面以后，就再也滑动不下来了。

**Comment by PossibleZero** [comment]
我试了下找到问题的原因了，跟我写的BaseFragment有关，我基类为了处理loading，和网络异常的处理逻辑，只是我不太明白，为啥这样的原因；
onCreateView的时候加载了自己定义的布局，我是将布局add进去的。
`
FrameLayout containerView = (FrameLayout) inflate.findViewById(R.id.fl_container); int contentId = getContentLayoutId(); if (contentId > 0) { mContentView = LayoutInflater.from(getActivity()).inflate(contentId, null); containerView.addView(mContentView, 0);`
现在造成的影响是，上拉加载能显示出来，下拉加载显示不出来，并且上部滑动到上面以后，就再也滑动不下来了。
我将布局直接加载进去，就没有问题，add到跟布局的view中，就会出现上述问题。
