### ISSUE TITLE
能否禁止上拉加载更多事件

### ISSUE THREAD

**Issue by fanhua0429** [bingoogolapple/BGARefreshLayout-Android#64]
因为服务器返回的数据小于一定数目，证明已经没有数据可以返回了，这个时候想禁用上拉事件，可以实现吗

**Comment by qinjuning** [comment]
用这个方法 setIsShowLoadingMoreView 多看看文档api之类的

**Comment by bingoogolapple** [comment]
@fanhua0429 仔细看 demo 哈，里面有演示这个这个怎么做，如果没有更多数据了就在 onBGARefreshLayoutBeginLoadingMore 方法里返回 false

**Comment by linzhengloser** [comment]
有什么有方法可以直接设置不触发上拉加载.
