### ISSUE TITLE
加载更多时，加载失败怎么处理呢?

### ISSUE THREAD

**Issue by epolar** [bingoogolapple/BGARefreshLayout-Android#65]
加载更多的时候，有可能会加载失败，比如说网络在加载过程中中断之类的，一般我们会在底部加个按钮让用户去手动点击，但是库本身似乎不支持，不知道用这个库的大家都是怎么处理这个问题的呢？

**Comment by bingoogolapple** [comment]
@epolar 没支持这个哈
