### ISSUE TITLE
BGARefreshLayout 内部嵌套一个FrameLayout FrameLayout里面是一个RecyclerView 上拉有问题

### ISSUE THREAD

**Issue by haonan1** [bingoogolapple/BGARefreshLayout-Android#79]
FrameLayout 是作为loading empty 和 error的视图展示 里面放了一个recycleview  我给FrameLayout设置高度为0dp weight 为1  在数据返回的时候 我调用自定义的framelayout 显示 我的recycleview 视图，这时候在上拉 recycleview不能滚动，并且上拉item 没有到最后一个，麻烦 请看下这个问题，或者给我一些建议

**Comment by haonan1** [comment]
现在解决的方法是 FrameLayout  里面是BGARefreshLayout BGARefreshLayout里面是recycleview 换了位置

**Comment by bingoogolapple** [comment]
是的
