### ISSUE TITLE
关于下拉加载更多效果

### ISSUE THREAD

**Issue by BaronZ** [bingoogolapple/BGARefreshLayout-Android#8]
关于下拉加载更多效果
我指的是，下拉加载更多，我们手动向上拉的时候，是没效果的，还以为不可以下拉加载，只有等松开的时候，才有转圈，体验不是很好。可否在上拉的时候有一个效果，就类似于下拉一样的“上拉加载更多”->"释放加载"？

**Comment by huclengyue** [comment]
是啊 要是这个功能也OK 那基本就可以日常使用了

**Comment by bingoogolapple** [comment]
@BaronZ @huclengyue 当初编写BGARefreshLayout-Android就想的是实现类似新浪微博下拉刷新和滚动到底部时加载更多的效果，在现在的基础上实现上拉和下拉时又同样地效果的话改动挺大的。这个月公司新项目搞完空了再搞。

**Comment by BaronZ** [comment]
期待: )

**Comment by doubleZuo** [comment]
同样期待。。
