### ISSUE TITLE
关闭下拉加载更多bug

### ISSUE THREAD

**Issue by BaronZ** [bingoogolapple/BGARefreshLayout-Android#9]
关闭下拉加载更多bug
在关闭了下拉加载更多之后，实际还是会触发加载加多，这里的关闭加载更多似乎只是没有显示加载更多的动画

**Comment by bingoogolapple** [comment]
和上拉加载更多不同，下拉刷新是用户手指拖动触发，拖到满足下拉刷新的条件时，肯定会触发下拉刷新事件，如果开发者不想加载更多数据，则在onBGARefreshLayoutBeginLoadingMore方法中不加载数据，并且调用mRefreshLayout.endLoadingMore()后马上就会关闭下拉加载更多。

**Comment by BaronZ** [comment]
这个应该还是一个Bug，你都不能加载更多了，不应该让用户去控制是否还能再实际再加载

**Comment by BaronZ** [comment]
`拖到满足下拉刷新的条件时，肯定会触发下拉刷新事件`
既然设置了不能加载更多，在上拉到刷新条件时就不应用触发刷新事件

**Comment by tangshengjun** [comment]
能否出一个eclipse 版本，AS 在国内很多东西下载不了。 或者给出相关jar 也行，非常谢谢哟
