### ISSUE TITLE
老问题，上拉加载view，不显示

### ISSUE THREAD

**Issue by AcgnCodeMonkey** [bingoogolapple/BGARefreshLayout-Android#90]
![image](https://cloud.githubusercontent.com/assets/19161307/18945693/48c9b390-865e-11e6-97d5-b42a37ae116c.png)

**Comment by AcgnCodeMonkey** [comment]
为什么有的界面能显示有的不行呢？

**Comment by bingoogolapple** [comment]
去看readme里的常见问题
